### ISSUE TITLE
Feature request: CRT GEOM OpenGL shader

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#10]
As GDash supports OpenGL shaders, one of the best shaders for CRT simulation called CRT GEOM (deluxe) would be nice to have as an additional shader effect. Would perfectly fit for retro C64 game!

Tried this one:
https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/crt-geom.glsl

Is shown in the options after renaming to .shader but does not do anything.

**Comment by revvv** [comment]
Looks like that GDash only supports XML shaders:
https://docs.libretro.com/development/shader/xml-shaders/

I'm not sure how to convert the *.glsl format to XML, if this is possible at all.

So I tried to hack the GDash code to load a GLSL shader. I could manage to load everything without error, but I don't see an effect... As I have no experience with shaders, I guess there is something missing.

So far I did:
- Add code from this example: https://moderncprogramming.com/loading-a-glsl-shader-from-file-in-opengl-using-pure-c/
- Modify [crt-geom.glsl](https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/crt-geom.glsl):
    - Comment #pragma's, otherwise syntax error
    - Split into two parts (vertex/fragment) and load separetely
    - Rename lum to lum1 in `saturation()`, otherwise syntax error

So probably this ends with "help wanted"...

**Comment by revvv** [comment]
New approach: I found a XML version of the shader here:
https://github.com/alunbestor/Boxer/blob/master/Resources/Shaders/crt-geom-interlaced-curved.shader

Modified for GDash: add version, disable CURVATURE, add interlace_detect

Start GDash with `-v` so that you can see why a shader does not get compiled.
If you need more shader log info I could add it, but the additional output is just "compile failed" or "main() not found".
(This requires to add `glGetProgramInfoLog`, `glGetShaderiv` and `glGetProgramiv`)

Please tell me if this does the job, so I can close the issue.

**Comment by cwscws** [comment]
I found shaders that are working with GDash, too:

https://github.com/guestrr/FS-UAE-Shaders/tree/master

Not all are working but these are (and have nice effects):
crt-caligari
crt-cgwg
crt-trinitron
crt-trinitron2
xbrz4x
xbrz6x

**Comment by revvv** [comment]
> 
> Is this already modified for GDash or do you still have to do that?
> 

It's already modified, although the original file already worked. I guess, I'll revert to the original. Maybe then it's easier to import a new version of the shader.
