### ISSUE TITLE
Stopping falling boulders (non-default gravity)

### ISSUE THREAD

**Issue by Dustin974** [revvv/gdash-export-CrLi#52]
This is just a small funny illogical feature, I don't know how it is in CLCK:
Rockford or a fly can sometimes stop a falling boulder if there's non-default gravity:

(1) Gravity up (or flying boulder in default gravity):
BR
BS
Move right and immediately left again.

(2) Gravity right:
SSSSR
SSSBS
(B is already falling state)
Move down.

These are the only cases I found. None can be mirrored. I think I know the technical reason: Falling boulders can not crush Rockford in delay state. This would perfectly explain why these two examples work, and only these.

**Comment by revvv** [comment]
Yeah, I guess many more examples like these can be found. The reason is how the cave elements are iterated.
See [Zoltan's explanation](https://github.com/revvv/gdash-export-CrLi/issues/42#issuecomment-1699726327).

You could prevent such cases by changing the iteration direction, but then you have the same problem with light elements again. Or ban light elements.
