### ISSUE TITLE
Windows freezes when resizing or moving game window (GTK+ mode)

### ISSUE THREAD

**Issue by BadDog73** [revvv/gdash-export-CrLi#57]
As title, the whole OS, mouse, freezes up while moving or scaling the window.  Pressing alt+tab restores operation, but I only discovered that accidentally.  Windows 10.

**Comment by revvv** [comment]
Yes, I know this feature from the beginning. I'm not sure if it occurs on Linux/Mac.

**Comment by cwscws** [comment]
No problem on MacOS

**Comment by revvv** [comment]
I found [GTK issue 5688](https://gitlab.gnome.org/GNOME/gtk/-/issues/5688) Strange, I know this bug so much longer...
I can add a workaround for now, because I don't expect any fixes for GTK3.

I don't like this freeze feature, too, once I'm done with testing I'll put it in.

Note, @zsommk already reported this: #49

**Comment by revvv** [comment]
Only occurs on Windows. Never seen on Linux/Mac.
